# Is Firm Facebook-Advertisable?

**Goal**: Tag companies founded/owned by entrepreneurs as likely **Facebook/Instagram advertisers** — i.e., B2C businesses whose product or service is *visual* or *experiential* and can be naturally promoted through a Facebook Page.

**What qualifies?**  
- Visual products: fashion, food, beauty, art, photography, home decor  
- Consumer experiences: restaurants, cafes, fitness studios, salons, events, travel  
- Consumer-facing digital brands: e-commerce, apps, media, subscription boxes  
- Local services people *choose* with emotion: wedding planners, photographers, gyms  

**What does NOT qualify?**  
- B2B/trade services (construction contractors, HVAC, trucking, accounting)  
- Legal / medical professional practices  
- Industrial / wholesale businesses  

**Approach**: Rule-based weighted keyword scoring on `company_name`, converted to a 0–1 confidence via sigmoid. Entirely local — no API calls.

## 1. Setup and Load Data

In [12]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print('Loading all_experience...', flush=True)
all_experience = pd.read_pickle('/shared/share_scp/coresignal/all_experience_AnalysisFile_latest.pkl')
print(f'Loaded {len(all_experience):,} rows, {all_experience.shape[1]} columns')
print('Columns:', list(all_experience.columns))

Loading all_experience...
Loaded 88,234,570 rows, 21 columns
Columns: ['member_id', 'title', 'company_name', 'company_url', 'date_from', 'date_to', 'duration', 'company_id', 'job_from', 'is_founder_only', 'is_owner_only', 'is_founder_or_owner', 'is_founder_or_owner_with_url', 'is_founder_or_owner_inc', 'is_cofounder_or_coowner_title', 'is_cofounder_only_title', 'is_coowner_only_title', 'long_title', 'franchise_founder_or_owner', 'franchise_owner', 'cofound_coown_same_url']

## 2. Filter to Entrepreneurs Only

In [13]:
# Determine which column flags entrepreneurs
if 'is_founder_or_owner' in all_experience.columns:
    entrepreneurs = all_experience[all_experience['is_founder_or_owner'] == True].copy()
elif 'is_founder_only' in all_experience.columns and 'is_owner_only' in all_experience.columns:
    entrepreneurs = all_experience[
        all_experience['is_founder_only'] | all_experience['is_owner_only']
    ].copy()
else:
    raise ValueError('No founder/owner flag found. Check column names above.')

print(f'Total entrepreneur rows     : {len(entrepreneurs):,}')
print(f'Unique company names        : {entrepreneurs["company_name"].nunique():,}')
print(f'Rows with null company_name : {entrepreneurs["company_name"].isna().sum():,}')

# Unique company names to score (deduplicated for speed)
unique_companies = (
    entrepreneurs['company_name']
    .dropna()
    .astype(str)
    .str.strip()
    .loc[lambda s: s != '']
    .unique()
)
print(f'Unique non-null company names to score: {len(unique_companies):,}')

Total entrepreneur rows     : 1,169,264
Unique company names        : 391,641
Rows with null company_name : 1,356
Unique non-null company names to score: 386,948

## 2 · Approach: BERT Embeddings + Supervised Learning

Instead of hand-crafted keyword rules, we use a data-driven approach:

1. **Sample 2,000 unique company names** at random and ask GPT-4o to label each as `yes` (likely Facebook/Instagram advertiser) or `no` (unlikely).
2. **Encode every name with BERT** (`all-MiniLM-L6-v2` via `sentence-transformers`), producing a 384-dimensional semantic embedding per name.
3. **Train a logistic regression** classifier on the 2,000-example labelled set, mapping embeddings → P(FB advertiser).
4. **Score all 386,948 unique company names** with the trained model and map probabilities to five ordered labels:

| P(yes) | Label |
|---|---|
| ≥ 0.80 | highly likely |
| 0.65 – 0.80 | likely |
| 0.35 – 0.65 | unclear |
| 0.20 – 0.35 | unlikely |
| &lt; 0.20 | highly unlikely |

In [27]:
# ── Install dependencies (only if missing) ───────────────────────────────────
import importlib, subprocess, sys

def _ensure(pkg, import_as=None):
    try:
        importlib.import_module(import_as or pkg)
    except ImportError:
        print(f"Installing {pkg}…")
        subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'], check=True)

_ensure('sentence-transformers', 'sentence_transformers')
_ensure('scikit-learn', 'sklearn')

# ── Core imports ──────────────────────────────────────────────────────────────
import re, json, time
import numpy as np
import pandas as pd
import openai

from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

LABEL_ORDER = ['highly likely', 'likely', 'unclear', 'unlikely', 'highly unlikely']

print("All imports OK.")

Installing sentence-transformers…
All imports OK.

In [31]:
# ── Sample 1,000 unique company names ────────────────────────────────────────
rng = np.random.default_rng(42)
unique_companies = entrepreneurs['company_name'].dropna().unique()
sample_2000 = rng.choice(unique_companies, size=1000, replace=False).tolist()

# ── Label with GPT-4o (binary: yes / no) ─────────────────────────────────────
# Uses `client` already in kernel scope.
LABEL_SYSTEM = """\
You are a business classifier.  For each company name, decide whether this company
would be likely to run paid ads on Facebook or Instagram.

Answer "yes" for visual / experiential B2C businesses:
  retail shops, beauty salons, gyms/yoga studios, restaurants, bakeries, cafés,
  fashion & apparel brands, photographers, florists, event planners, home décor
  brands, travel agencies, pet groomers, children's activity centers, wellness
  coaches, art studios, entertainment venues, e-commerce shops, candle companies.

Answer "no" for B2B, industrial, or professional-services businesses:
  plumbers, HVAC contractors, freight/trucking, law firms, accounting firms,
  IT consulting, construction companies, manufacturers, wholesale distributors,
  staffing agencies, financial advisors, medical/dental practices.

When truly ambiguous, prefer "no".

Respond ONLY with a JSON object mapping each name exactly as given to "yes" or "no".
No extra keys, no commentary."""

gpt2000_labels: dict = {}
BATCH = 50
batches = [sample_2000[i:i+BATCH] for i in range(0, len(sample_2000), BATCH)]

print(f"Sending {len(sample_2000):,} names to GPT-4o in {len(batches)} batches…")

for idx, batch in enumerate(batches):
    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model='gpt-4o',
                messages=[
                    {'role': 'system', 'content': LABEL_SYSTEM},
                    {'role': 'user',   'content': json.dumps(batch)},
                ],
                temperature=0,
                response_format={"type": "json_object"},
            )
            raw   = resp.choices[0].message.content.strip()
            chunk = json.loads(raw)
            gpt2000_labels.update(chunk)
            print(f"  Batch {idx+1}/{len(batches)}: {len(chunk)} labels")
            break
        except Exception as e:
            print(f"  Batch {idx+1} attempt {attempt+1} failed: {e}")
            time.sleep(3)

# Normalise keys and values
gpt2000_labels = {str(k).strip(): str(v).strip().lower()
                  for k, v in gpt2000_labels.items()}

yes_n = sum(1 for v in gpt2000_labels.values() if v == 'yes')
no_n  = sum(1 for v in gpt2000_labels.values() if v == 'no')
print(f"\nLabelled: {len(gpt2000_labels):,}  |  yes={yes_n:,}  no={no_n:,}")

Sending 1,000 names to GPT-4o in 20 batches…
  Batch 1/20: 50 labels
  Batch 2/20: 50 labels
  Batch 3/20: 50 labels
  Batch 4/20: 50 labels
  Batch 5/20: 50 labels
  Batch 6/20: 50 labels
  Batch 7/20: 50 labels
  Batch 8/20: 50 labels
  Batch 9/20: 50 labels
  Batch 10/20: 50 labels
  Batch 11/20: 50 labels
  Batch 12/20: 50 labels
  Batch 13/20: 50 labels
  Batch 14/20: 50 labels
  Batch 15/20: 50 labels
  Batch 16/20: 50 labels
  Batch 17/20: 50 labels
  Batch 18/20: 50 labels
  Batch 19/20: 50 labels
  Batch 20/20: 50 labels

Labelled: 1,000  |  yes=317  no=683

## 3 · Train BERT + Logistic Regression Classifier

In [32]:
# ── Load BERT model ───────────────────────────────────────────────────────────
print("Loading sentence-transformers model (all-MiniLM-L6-v2)…")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

# ── Prepare training data (clean yes/no labels only) ─────────────────────────
train_names = [n for n in sample_2000 if gpt2000_labels.get(n) in ('yes', 'no')]
train_y     = np.array([1 if gpt2000_labels[n] == 'yes' else 0 for n in train_names])
print(f"Training examples: {len(train_names):,}  (yes={train_y.sum():,}  no={(1-train_y).sum():,})")

# ── Encode training names with BERT ──────────────────────────────────────────
print("Encoding training names with BERT…")
train_X = bert_model.encode(
    train_names, batch_size=256, show_progress_bar=True, normalize_embeddings=True
)

# ── Train logistic regression with 5-fold cross-validation ───────────────────
print("Training logistic regression (5-fold CV)…")
clf    = LogisticRegression(C=1.0, max_iter=1000, random_state=42)
cv_auc = cross_val_score(clf, train_X, train_y, cv=5, scoring='roc_auc')
print(f"  CV AUC: {cv_auc.mean():.3f} ± {cv_auc.std():.3f}")

clf.fit(train_X, train_y)
print("Model trained and ready.")

Loading sentence-transformers model (all-MiniLM-L6-v2)…

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 10066.96it/s]

Training examples: 986  (yes=310  no=676)
Encoding training names with BERT…

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.04it/s]

Training logistic regression (5-fold CV)…
  CV AUC: 0.882 ± 0.018
Model trained and ready.

In [35]:
# ── Hold-out test: draw 200 *new* names (never seen during training) ──────────
# Exclude the 1,000 training names from the pool
train_set      = set(sample_2000)
holdout_pool   = [n for n in unique_companies.tolist() if n not in train_set]
holdout_names  = rng.choice(holdout_pool, size=200, replace=False).tolist()

print(f"Sending 200 fresh names to GPT-4o for hold-out labels…")
holdout_labels: dict = {}
ho_batches = [holdout_names[i:i+50] for i in range(0, 200, 50)]
for idx, batch in enumerate(ho_batches):
    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model='gpt-4o',
                messages=[
                    {'role': 'system', 'content': LABEL_SYSTEM},
                    {'role': 'user',   'content': json.dumps(batch)},
                ],
                temperature=0,
                response_format={"type": "json_object"},
            )
            chunk = json.loads(resp.choices[0].message.content.strip())
            holdout_labels.update(chunk)
            print(f"  Batch {idx+1}/4: {len(chunk)} labels")
            break
        except Exception as e:
            print(f"  Batch {idx+1} attempt {attempt+1} failed: {e}")
            time.sleep(3)

holdout_labels = {str(k).strip(): str(v).strip().lower()
                  for k, v in holdout_labels.items()}

# Encode and score the hold-out names with the trained model
clean_ho = [(n, holdout_labels[n]) for n in holdout_names
            if holdout_labels.get(n) in ('yes', 'no')]
ho_names, ho_true = zip(*clean_ho)
ho_y   = np.array([1 if v == 'yes' else 0 for v in ho_true])
ho_X   = bert_model.encode(list(ho_names), batch_size=256,
                            show_progress_bar=False, normalize_embeddings=True)
ho_probs = clf.predict_proba(ho_X)[:, 1]

from sklearn.metrics import roc_auc_score
ho_auc = roc_auc_score(ho_y, ho_probs)
print(f"\nHold-out test  (n={len(ho_y)}, yes={ho_y.sum()}, no={(1-ho_y).sum()})")
print(f"  AUC (out-of-sample): {ho_auc:.3f}")
print(f"  Train CV AUC       : {cv_auc.mean():.3f} ± {cv_auc.std():.3f}")

Sending 200 fresh names to GPT-4o for hold-out labels…
  Batch 1/4: 50 labels
  Batch 2/4: 50 labels
  Batch 3/4: 50 labels
  Batch 4/4: 50 labels

Hold-out test  (n=199, yes=44, no=155)
  AUC (out-of-sample): 0.883
  Train CV AUC       : 0.882 ± 0.018

In [33]:
# ── Embed and score all unique company names ──────────────────────────────────
print(f"Encoding {len(unique_companies):,} unique company names with BERT…")
all_X = bert_model.encode(
    unique_companies.tolist(), batch_size=512,
    show_progress_bar=True, normalize_embeddings=True
)

# Predict P(yes = Facebook advertiser)
probs = clf.predict_proba(all_X)[:, 1]

def prob_to_label(p):
    if   p >= 0.80: return 'highly likely'
    elif p >= 0.65: return 'likely'
    elif p >= 0.35: return 'unclear'
    elif p >= 0.20: return 'unlikely'
    else:           return 'highly unlikely'

company_scores = pd.DataFrame({
    'company_name'     : unique_companies,
    'fb_ad_prob'       : probs,
    'fb_ad_likelihood' : pd.Categorical(
                             [prob_to_label(p) for p in probs],
                             categories=LABEL_ORDER, ordered=True
                         ),
})

print("\nDistribution of fb_ad_likelihood:")
for lbl in LABEL_ORDER:
    n = (company_scores['fb_ad_likelihood'] == lbl).sum()
    print(f"  {lbl:<20}: {n:8,}  ({n/len(company_scores):.1%})")

Encoding 391,641 unique company names with BERT…

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 765/765 [29:14<00:00,  2.29s/it]

Distribution of fb_ad_likelihood:
  highly likely       :   14,983  (3.8%)
  likely              :   33,763  (8.6%)
  unclear             :  101,666  (26.0%)
  unlikely            :   85,510  (21.8%)
  highly unlikely     :  155,719  (39.8%)

In [34]:
# ── Merge scores onto entrepreneur rows ───────────────────────────────────────
_drop = [c for c in ['raw_score', 'confidence', 'fb_ad_likelihood',
                     'fb_ad_likelihood_final', 'matched_keywords', 'fb_ad_prob']
         if c in entrepreneurs.columns]
if _drop:
    entrepreneurs = entrepreneurs.drop(columns=_drop)

entrepreneurs = entrepreneurs.merge(
    company_scores[['company_name', 'fb_ad_prob', 'fb_ad_likelihood']],
    on='company_name',
    how='left'
)

print(f"Entrepreneurs with a score: {entrepreneurs['fb_ad_prob'].notna().sum():,}")
print("\nDistribution of fb_ad_likelihood across entrepreneur rows:")
for lbl in LABEL_ORDER:
    n = (entrepreneurs['fb_ad_likelihood'] == lbl).sum()
    print(f"  {lbl:<20}: {n:8,}  ({n/len(entrepreneurs):.1%})")

Entrepreneurs with a score: 1,167,908

Distribution of fb_ad_likelihood across entrepreneur rows:
  highly likely       :   40,864  (3.5%)
  likely              :   93,036  (8.0%)
  unclear             :  298,599  (25.5%)
  unlikely            :  263,075  (22.5%)
  highly unlikely     :  472,334  (40.4%)

## 4 · Random Sample for Manual Validation

Review 40 rows from each label category (200 total).  
Ask: *"Is `fb_ad_likelihood` the right label for this company?"*

| Column | Meaning |
|---|---|
| `company_name` | Raw name from LinkedIn |
| `fb_ad_likelihood` | Predicted label (5-level) |
| `fb_ad_prob` | P(Facebook advertiser) from the BERT + logistic regression model |

In [ ]:
import random
random.seed(42)
np.random.seed(42)

# Draw up to 40 names from each of the 5 categories → up to 200 rows total
N_PER_LABEL = 40
frames = []
for label in LABEL_ORDER:
    subset = company_scores[company_scores['fb_ad_likelihood'] == label]
    n = min(N_PER_LABEL, len(subset))
    if n > 0:
        frames.append(subset.sample(n=n, random_state=42))
        print(f"  {label:<20}: sampled {n} of {len(subset):,}")

validation_sample = (
    pd.concat(frames)
    .sample(frac=1, random_state=99)   # shuffle so labels are interleaved
    .reset_index(drop=True)
)

display_cols = ['company_name', 'fb_ad_likelihood', 'fb_ad_prob']

print(f"\nTotal validation sample: {len(validation_sample)} rows")
print("Review the table and note mis-classifications.\n")

pd.set_option('display.max_rows', 210)
pd.set_option('display.max_colwidth', 80)
pd.set_option('display.float_format', '{:.3f}'.format)

validation_sample[display_cols]

  highly likely      : sampled 40 of 25,375
  likely             : sampled 40 of 7,213
  unclear            : sampled 40 of 348,072
  unlikely           : sampled 40 of 1,902
  highly unlikely    : sampled 40 of 4,386

Total validation sample: 200 rows
Review the table and note mis-classifications.

,company_name,fb_ad_likelihood,confidence,raw_score,matched_keywords
0,Sigmon Wealth Management,unlikely,0.269,-1.000,'Wealth Management'(-1.0)
1,"Heritage Asset Management, LLC",unlikely,0.269,-1.000,'Asset Management'(-1.0)
2,Pats Cleaning Service,highly unlikely,0.119,-2.000,'Cleaning Service'(-2.0)
3,Knewsco Digital Inc.,likely,0.690,0.800,'Digital'(+0.8)
4,Tidus Consulting,unclear,0.500,0.000,(none)
5,L&C Landholdings LLC,unclear,0.500,0.000,(none)
6,Rylie Doo’s,unclear,0.500,0.000,(none)
7,"Barnett Marketing and Sales, LLC",highly likely,0.818,1.500,'Marketing'(+1.5)
8,IT Consulting Services,unlikely,0.269,-1.000,'IT Consulting'(-1.0)
9,Coastal Legal Counsel,highly unlikely,0.182,-1.500,'Counsel'(-1.5)
10,Liberty Golden Realty and Financial,unclear,0.500,0.000,(none)
11,Mevaser Tech,likely,0.622,0.500,'Tech'(+0.5)
12,BISSource Consulting Group (BCG),unlikely,0.310,-0.800,'Consulting Group'(-0.8)
13,Guardian Insurance Agency LLC,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
14,Aislinn's Mobile Notary,likely,0.690,0.800,'Mobile'(+0.8)
15,CBR Roofing Plus Maintenance,highly unlikely,0.076,-2.500,'Roofing'(-2.5)
16,New York Dog House™ / New York Burger House™,highly likely,0.943,2.800,'Burger'(+2.8)
17,Bronx.Tech,likely,0.622,0.500,'Tech'(+0.5)
18,Bean Town Coffee House & Bakery,highly likely,0.943,2.800,'Bakery'(+2.8)
19,"Vision Focus Business Consulting,LLC",unlikely,0.310,-0.800,'Business Consulting'(-0.8)
20,Versatile Web Technologies,likely,0.690,0.800,'Web'(+0.8)
21,Digital Dust,likely,0.690,0.800,'Digital'(+0.8)
22,Prime Pet Box,unclear,0.500,0.000,(none)
23,Gray Bike Software,likely,0.622,0.500,'Software'(+0.5)
24,ERP Software Solutions,unlikely,0.378,-0.500,'Software'(+0.5); 'ERP'(-1.0)
25,Bloom Online Business Management,likely,0.690,0.800,'Online'(+0.8)
26,Harvester Veterinary Hospital of Burr Ridge,highly unlikely,0.182,-1.500,'Hospital'(-1.5)
27,"Internet Easy-Access, Inc",likely,0.690,0.800,'Internet'(+0.8)
28,"SPINE LIFE CHIROPRACTIC, LLC",unclear,0.500,0.000,(none)
29,One Foot Over,unclear,0.500,0.000,(none)
30,Arch Consulting Group,unlikely,0.310,-0.800,'Consulting Group'(-0.8)
31,Eyedip,unclear,0.500,0.000,(none)
32,Cheshire Wellness Center,highly likely,0.943,2.800,'Wellness Center'(+2.8)
33,Shapemaker,unclear,0.500,0.000,(none)
34,Costin-Hubert Insurance Agency,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
35,Christian Brothers Roofing & Contracting,highly unlikely,0.076,-2.500,'Roofing'(-2.5)
36,Gatsby Technology Inc.,likely,0.622,0.500,'Technology'(+0.5)
37,The Minias Law Firm,highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
38,ALL TURF LLC,highly unlikely,0.076,-2.500,'TURF'(-2.5)
39,"Web Optimization, Inc.",likely,0.690,0.800,'Web'(+0.8)
40,"Liquid Energy Cafe, LLC",highly likely,0.943,2.800,'Cafe'(+2.8)
41,Tech Fall Attire,likely,0.622,0.500,'Tech'(+0.5)
42,410 Consulting,unclear,0.500,0.000,(none)
43,Xtreme Hauling,highly unlikely,0.119,-2.000,'Hauling'(-2.0)
44,Marquee Mobile,likely,0.690,0.800,'Mobile'(+0.8)
45,Chaup (Merged with HeliosAltas),unclear,0.500,0.000,(none)
46,Glow Mobile Spray Tanning,highly likely,0.964,3.300,'Glow'(+2.5); 'Mobile'(+0.8)
47,"Steel Blue Fabrication, LLC",highly unlikely,0.076,-2.500,'Fabrication'(-2.5)
48,The Compuclinic/Catalyst IT Solutions,unlikely,0.269,-1.000,'IT Solutions'(-1.0)
49,Fusion Marketing,highly likely,0.818,1.500,'Marketing'(+1.5)
50,"Joelle Rose Szlosek, LLC",unclear,0.500,0.000,(none)
51,Owoh Consulting Group,unlikely,0.310,-0.800,'Consulting Group'(-0.8)
52,SAB LLC - dba Cork - A Wine Bar,highly likely,0.943,2.800,'Wine Bar'(+2.8)
53,Atticus Wealth Management,unlikely,0.269,-1.000,'Wealth Management'(-1.0)
54,LaserXD Sailing,unclear,0.500,0.000,(none)
55,Linka Digital,likely,0.690,0.800,'Digital'(+0.8)
56,Amorist Media,unclear,0.500,0.000,(none)
57,Landscape Ecology,unclear,0.500,0.000,(none)
58,"Aldana Trucking, LLC",highly unlikely,0.119,-2.000,'Trucking'(-2.0)
59,"Applauso Italian Learning Center, LLC",highly likely,0.881,2.000,'Learning Center'(+2.0)
60,Rockstar Remodel,highly unlikely,0.076,-2.500,'Remodel'(-2.5)
61,Bluebonnet Speech Pathology,highly unlikely,0.182,-1.500,'Pathology'(-1.5)
62,"Roadrunner Digital Mining, LLC",likely,0.690,0.800,'Digital'(+0.8)
63,"Pool-Martin Insurance Agency, Inc.",unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
64,"M&M Creek Valley Farm, LLC",unclear,0.500,0.000,(none)
65,The Black Wealth Builder,highly unlikely,0.076,-2.500,'Builder'(-2.5)
66,"The Bazleh Law Firm, P.C.",highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
67,InteropSoft,unclear,0.500,0.000,(none)
68,Shark Promotional Products,unclear,0.500,0.000,(none)
69,MoZo Software LLC,likely,0.622,0.500,'Software'(+0.5)
70,[ocn]CrossFit L.L.C.,highly likely,0.943,2.800,'CrossFit'(+2.8)
71,"Nadine Kureghian Insurance Agency, Inc.",unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
72,Borgmann Construction Inc.,highly unlikely,0.076,-2.500,'Construction Inc'(-2.5)
73,Insurance Broker,unlikely,0.269,-1.000,'Insurance Broker'(-1.0)
74,Mountaineer CrossFit,highly likely,0.943,2.800,'CrossFit'(+2.8)
75,Silver Bullet Technology Inc.,likely,0.622,0.500,'Technology'(+0.5)
76,"The Mayvin Consulting Group, Inc",unlikely,0.310,-0.800,'Consulting Group'(-0.8)
77,Down Best Web Solutions,likely,0.690,0.800,'Web'(+0.8)
78,"S2 Consulting Firm, LLC",unlikely,0.310,-0.800,'Consulting Firm'(-0.8)
79,Hello Holiday,unclear,0.500,0.000,(none)
80,"The Darlington Law Firm, PLLC.",highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
81,cabi wardrobe stylist,highly likely,0.924,2.500,'wardrobe'(+2.5)
82,Tech on Tap Jax,likely,0.622,0.500,'Tech'(+0.5)
83,McCann Lawn Care,highly unlikely,0.076,-2.500,'Lawn Care'(-2.5)
84,All Creative Executions (ACE Marketing),highly likely,0.818,1.500,'Marketing'(+1.5)
85,Energy Exchange Wellness Spa,highly likely,0.953,3.000,'Spa'(+3.0)
86,aesthete mercantile + dry goods,unclear,0.500,0.000,(none)
87,LUIS ERAZO TRUCKING,highly unlikely,0.119,-2.000,'TRUCKING'(-2.0)
88,Yankee Bravo Digital Marketing,highly likely,0.997,5.800,'Digital Marketing'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8)
89,Joseph M. Derby Business Consulting,unlikely,0.310,-0.800,'Business Consulting'(-0.8)
90,"Sandy Bottom Boutique, LLC upscale-resale",highly likely,0.924,2.500,'Boutique'(+2.5)
91,Elephant Key Marketing,highly likely,0.818,1.500,'Marketing'(+1.5)
92,Team Us Small Business Consulting LLC,unlikely,0.310,-0.800,'Business Consulting'(-0.8)
93,Lady J's Bakery,highly likely,0.943,2.800,'Bakery'(+2.8)
94,First Class Masonry,highly unlikely,0.076,-2.500,'Masonry'(-2.5)
95,Orleans Insurance Agency LLC,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
96,JOChavarin Consulting Group,unlikely,0.310,-0.800,'Consulting Group'(-0.8)
97,Datahead Software Solutions,likely,0.622,0.500,'Software'(+0.5)
98,Educated and Elevated,unclear,0.500,0.000,(none)
99,HSL Digital,likely,0.690,0.800,'Digital'(+0.8)
100,"Lillian & Associates Insurance Agency, Inc",unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
101,"Clear Sky Solar, Inc.",unclear,0.500,0.000,(none)
102,Tyc00n Software,likely,0.622,0.500,'Software'(+0.5)
103,Max Velocity Motorsports & Fabrication LLC,highly unlikely,0.076,-2.500,'Fabrication'(-2.5)
104,Mountain Flower Apparel,highly likely,0.953,3.000,'Apparel'(+3.0)
105,Software Engineering Professionals (SEP),likely,0.622,0.500,'Software'(+0.5)
106,Meal Plan Rockstar Online Course,likely,0.690,0.800,'Online'(+0.8)
107,Red's Vape Cloud,likely,0.622,0.500,'Cloud'(+0.5)
108,"Conway Lawn Care, Inc.",highly unlikely,0.076,-2.500,'Lawn Care'(-2.5)
109,Refugio Radiology,highly unlikely,0.182,-1.500,'Radiology'(-1.5)
110,Green Valley Insurance Agency,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
111,Subtle Tech,likely,0.622,0.500,'Tech'(+0.5)
112,"Schrimpf Insurance Agency, LLC (Allstate Exclusive Agent)",unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
113,"GPS Management Consulting, Corp.",unlikely,0.310,-0.800,'Management Consulting'(-0.8)
114,"Paceline Wealth Management, LLC",unlikely,0.269,-1.000,'Wealth Management'(-1.0)
115,Ahmadeus Technology Boutique,highly likely,0.953,3.000,'Boutique'(+2.5); 'Technology'(+0.5)
116,"The Bloom Jewelry, Inc",highly likely,0.953,3.000,'Jewelry'(+3.0)
117,"Alpenglow Mobile Massage Therapy, LLC",highly likely,0.978,3.800,'Massage'(+3.0); 'Mobile'(+0.8)
118,Wildeye Winery,highly likely,0.943,2.800,'Winery'(+2.8)
119,ORIENTAL HEALING OASIS & WELLNESS CENTER,highly likely,0.943,2.800,'WELLNESS CENTER'(+2.8)
120,IHT Insurance Agency Group,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
121,Tech-Angeles,likely,0.622,0.500,'Tech'(+0.5)
122,Pilates by Nancy,highly likely,0.943,2.800,'Pilates'(+2.8)
123,"Bloom Between, LLC",unclear,0.500,0.000,(none)
124,Tom Hamiltons Painting Service,unclear,0.500,0.000,(none)
125,"Redding IT Solutions, LLC",unlikely,0.269,-1.000,'IT Solutions'(-1.0)
126,Independent Insurance Agency,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
127,"O-Web Technologies, Ltd.",likely,0.690,0.800,'Web'(+0.8)
128,Timber Hill Veterinary Services,unclear,0.500,0.000,(none)
129,Invescore Global Asset Management LLC,unlikely,0.269,-1.000,'Asset Management'(-1.0)
130,33 rd Annual Tinsel Triathlon & 5K,unclear,0.500,0.000,(none)
131,JLB Strategy Consulting,unlikely,0.310,-0.800,'Strategy Consulting'(-0.8)
132,Laura Gordillo Photography,unclear,0.500,0.000,(none)
133,Trujillo Law Firm,highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
134,Lizard Thicket Boutique- Boulder,highly likely,0.924,2.500,'Boutique'(+2.5)
135,Angel's Hope,unclear,0.500,0.000,(none)
136,APP ARCHITECTS,likely,0.690,0.800,'APP'(+0.8)
137,Maple Ridge Photography,unclear,0.500,0.000,(none)
138,Prism Art and Design,unclear,0.500,0.000,(none)
139,Marie's Pet Grooming,highly likely,0.924,2.500,'Pet Grooming'(+2.5)
140,"Skull Creek Greek, LLC",unclear,0.500,0.000,(none)
141,"Proficio Consulting Group, LLC",unlikely,0.310,-0.800,'Consulting Group'(-0.8)
142,"Prime Seamless Gutters & Roofing, LLC",highly unlikely,0.076,-2.500,'Roofing'(-2.5)
143,Indaba Music,unclear,0.500,0.000,(none)
144,Thurman Technology,likely,0.622,0.500,'Technology'(+0.5)
145,Paint Genius,unclear,0.500,0.000,(none)
146,Brackett's Lawn Care,highly unlikely,0.076,-2.500,'Lawn Care'(-2.5)
147,OJ IT Solutions,unlikely,0.269,-1.000,'IT Solutions'(-1.0)
148,"Table Mountain Ventures, LLC & TMV Consulting Group",unlikely,0.310,-0.800,'Consulting Group'(-0.8)
149,"Dozier Law Firm, PLLC",highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
150,Quiet Storm Massage & Bodywork,highly likely,0.953,3.000,'Massage'(+3.0)
151,Roofing & Exterior Contractor - Independent Contractor,highly unlikely,0.076,-2.500,'Roofing'(-2.5)
152,"Sierra West Masonry, Inc.",highly unlikely,0.076,-2.500,'Masonry'(-2.5)
153,Nuffer Fitness,unclear,0.500,0.000,(none)
154,Mobile Realty LLC,likely,0.690,0.800,'Mobile'(+0.8)
155,Cottage Inn Cafe Restaurant + Bar,highly likely,0.943,2.800,'Cafe'(+2.8)
156,Method Financial Planning,unlikely,0.269,-1.000,'Financial Planning'(-1.0)
157,Roscoe Sports Technology,likely,0.622,0.500,'Technology'(+0.5)
158,Swell Creative Group,unclear,0.500,0.000,(none)
159,Woodland & Ivory,unclear,0.500,0.000,(none)
160,Headlines Salon & Spa,highly likely,0.953,3.000,'Spa'(+3.0)
161,"EJS Equities, LLC",unclear,0.500,0.000,(none)
162,Parlay App,likely,0.690,0.800,'App'(+0.8)
163,North Central Marketing,highly likely,0.818,1.500,'Marketing'(+1.5)
164,Simply Me Collections,unclear,0.500,0.000,(none)
165,Rivera Law Firm,highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
166,Ramen Supply Company,highly likely,0.943,2.800,'Ramen'(+2.8)
167,"Simply Two Consulting Firm, LLC",unlikely,0.310,-0.800,'Consulting Firm'(-0.8)
168,Picture Perfect Photo Booth LLC,highly likely,0.943,2.800,'Photo Booth'(+2.8)
169,CrossFit Santa Monica,highly likely,0.943,2.800,'CrossFit'(+2.8)
170,Idyllix Corporation,unclear,0.500,0.000,(none)
171,Hale Speech Pathology,highly unlikely,0.182,-1.500,'Pathology'(-1.5)
172,M3 Digital Marketing,highly likely,0.997,5.800,'Digital Marketing'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8)
173,"Andrew Vaughn Law Firm, P.C.",highly unlikely,0.182,-1.500,'Law Firm'(-1.5)
174,Wild Horses Mobile Wash,likely,0.690,0.800,'Mobile'(+0.8)
175,Kristin Marie Jewelry,highly likely,0.953,3.000,'Jewelry'(+3.0)
176,Bavarian Window Cleaning - (360)-701-0644 - https://bavarianwindowcleaning.com,highly unlikely,0.119,-2.000,'Window Cleaning'(-2.0)
177,ULI Tech,likely,0.622,0.500,'Tech'(+0.5)
178,E-Commerce Processing,highly likely,0.953,3.000,'E-Commerce'(+3.0)
179,Blin Software CO. LTD.,likely,0.622,0.500,'Software'(+0.5)
180,Rusch Technology Services LLC,likely,0.622,0.500,'Technology'(+0.5)
181,Ourania Thisavrous Boutique,highly likely,0.924,2.500,'Boutique'(+2.5)
182,Shotgun Logistics Co.,highly unlikely,0.119,-2.000,'Logistics Co'(-2.0)
183,Lilana's Art Boutique,highly likely,0.924,2.500,'Boutique'(+2.5)
184,"G’s Trucking, LLC - Transportation",highly unlikely,0.119,-2.000,'Trucking'(-2.0)
185,John Fiorentino Insurance Agency,unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
186,BETA Consulting Group,unlikely,0.310,-0.800,'Consulting Group'(-0.8)
187,"Southard Strategies, LLC",unclear,0.500,0.000,(none)
188,"Premier Technology Services, Inc.",likely,0.622,0.500,'Technology'(+0.5)
189,Remodel Boston,highly unlikely,0.076,-2.500,'Remodel'(-2.5)
190,Mage Mind Software LLC,likely,0.622,0.500,'Software'(+0.5)
191,"NORTHSTAR MEDICAL GROUP, INC.",highly unlikely,0.182,-1.500,'MEDICAL GROUP'(-1.5)
192,"""The South"" Insurance Agency",unlikely,0.269,-1.000,'Insurance Agency'(-1.0)
193,"Turner & Sons Roofing & Siding, LLC",highly unlikely,0.076,-2.500,'Roofing'(-2.5)
194,"Eric Marquez, Attorney at Law",highly unlikely,0.182,-1.500,'Attorney'(-1.5)
195,Chicago Startup Factory,likely,0.622,0.500,'Startup'(+0.5)
196,Legends Trucking & Transportation LLC,highly unlikely,0.119,-2.000,'Trucking'(-2.0)
197,Michael trucking serv.,highly unlikely,0.119,-2.000,'trucking'(-2.0)
198,Clear Concept Fitness (Marketing/Social Media Agency),highly likely,0.999,7.000,'Social Media Agency'(+3.5); 'Social Media'(+2.0); 'Marketing'(+1.5)
199,M Petersen Consulting Group,unlikely,0.310,-0.800,'Consulting Group'(-0.8)

## 5 · GPT-4o Validation — Independent Classification of the 200-Name Sample

Send the validation sample to GPT-4o and ask it to assign the same 5-level label independently.  
Compare GPT's answers against the BERT model's labels, print every disagreement, and report the agreement rate.

**Workflow:**
1. Run the **API call cell** — sends all 200 names to GPT-4o in batches of 50
2. Run the **comparison cell** — prints agreement rate and lists every disagreement

In [18]:
import openai
import json
import time

# ── API key ───────────────────────────────────────────────────────────────────
# Rotate this key at https://platform.openai.com/api-keys after use.
# import os  # (already imported above)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
client = openai.OpenAI(api_key=OPENAI_API_KEY)

VALID_LABELS = ['highly likely', 'likely', 'unclear', 'unlikely', 'highly unlikely']

SYSTEM_PROMPT = """You are a business analyst helping classify company names.

The task: given a list of company names, decide how likely each company is to run
Facebook / Instagram paid advertising — i.e. does it sell a *visual* or *experiential*
consumer product or service that would make a natural Facebook Page?

Examples that are POSITIVE (run FB ads):
  fashion boutiques, beauty salons, restaurants, bakeries, gyms/yoga studios,
  photographers, florists, event planners, home decor brands, travel agencies,
  e-commerce shops, candle companies, pet groomers, children's activity centers.

Examples that are NEGATIVE (unlikely to run FB ads):
  plumbers, HVAC contractors, freight/trucking companies, law firms, accounting
  firms, B2B software companies, medical practices, industrial manufacturers,
  janitorial services, funeral homes.

Assign each company EXACTLY one of these five labels (use the exact string):
  highly likely | likely | unclear | unlikely | highly unlikely

Return ONLY a JSON array of objects with keys "company_name" and "label".
No explanation, no markdown fences, just the raw JSON array."""

def classify_batch(names, batch_size=50, pause=1.0):
    """Send names to GPT-4o in batches; return {name: label} dict."""
    results = {}
    batches = [names[i:i+batch_size] for i in range(0, len(names), batch_size)]
    for batch_idx, batch in enumerate(batches):
        numbered = '\n'.join(f'{i+1}. {n}' for i, n in enumerate(batch))
        user_msg = (
            f'Classify these {len(batch)} company names:\n\n{numbered}\n\n'
            'Return a JSON array: [{"company_name": "...", "label": "..."}, ...]'
        )
        for attempt in range(3):
            try:
                resp = client.chat.completions.create(
                    model='gpt-4o',
                    messages=[
                        {'role': 'system', 'content': SYSTEM_PROMPT},
                        {'role': 'user',   'content': user_msg},
                    ],
                    temperature=0,
                    max_tokens=4096,
                )
                raw = resp.choices[0].message.content.strip()
                # Strip accidental markdown fences
                if raw.startswith('```'):
                    raw = '\n'.join(raw.split('\n')[1:])
                if raw.endswith('```'):
                    raw = '\n'.join(raw.split('\n')[:-1])
                parsed = json.loads(raw)
                for item in parsed:
                    name  = item.get('company_name', '').strip()
                    label = item.get('label', '').strip().lower()
                    if label not in VALID_LABELS:
                        label = 'unclear'
                    results[name] = label
                print(f'  Batch {batch_idx+1}/{len(batches)}: {len(parsed)} labels received')
                break
            except Exception as e:
                print(f'  Batch {batch_idx+1} attempt {attempt+1} failed: {e}')
                time.sleep(3)
        time.sleep(pause)
    return results

# ── Run classification ────────────────────────────────────────────────────────
names_to_classify = validation_sample['company_name'].tolist()
print(f'Sending {len(names_to_classify)} names to GPT-4o...')
gpt_labels = classify_batch(names_to_classify)

# Attach GPT labels to validation sample
validation_sample['gpt_label'] = validation_sample['company_name'].map(gpt_labels)
print(f'\nGPT labels received for {validation_sample["gpt_label"].notna().sum()} / {len(validation_sample)} names')
print('\nGPT label distribution:')
print(validation_sample['gpt_label'].value_counts().reindex(VALID_LABELS).to_string())

Sending 200 names to GPT-4o...
  Batch 1/4: 50 labels received
  Batch 2/4: 50 labels received
  Batch 3/4: 50 labels received
  Batch 4/4: 50 labels received

GPT labels received for 200 / 200 names

GPT label distribution:
gpt_label
highly likely      24
likely             22
unclear            45
unlikely           42
highly unlikely    67

In [19]:
# ── Compare BERT model vs GPT-4o ─────────────────────────────────────────────
compare = validation_sample[['company_name', 'fb_ad_likelihood', 'gpt_label', 'fb_ad_prob']].copy()
compare = compare[compare['gpt_label'].notna()]
compare['agree'] = compare['fb_ad_likelihood'] == compare['gpt_label']

n_total = len(compare)
n_agree = compare['agree'].sum()
n_wrong = n_total - n_agree
pct_ok  = n_agree / n_total * 100

print('=' * 60)
print(f'  Total compared  : {n_total}')
print(f'  Model agree     : {n_agree}  ({pct_ok:.1f}%)')
print(f'  Disagreements   : {n_wrong}  ({100 - pct_ok:.1f}%)')
print('=' * 60)

# ── Disagreement detail ───────────────────────────────────────────────────────
wrong = compare[~compare['agree']].copy()

if len(wrong) == 0:
    print('\nPerfect agreement — no disagreements!')
else:
    print(f'\n{"#":<4}  {"Company Name":<40}  {"BERT Model":<18}  {"GPT-4o":<18}  P(yes)')
    print('-' * 95)
    for i, (_, row) in enumerate(wrong.iterrows(), 1):
        print(f'{i:<4}  {str(row["company_name"]):<40}  '
              f'{row["fb_ad_likelihood"]:<18}  {row["gpt_label"]:<18}  {row["fb_ad_prob"]:.3f}')

    print()
    print('Disagreement breakdown by direction:')
    direction = wrong.groupby(['fb_ad_likelihood', 'gpt_label']).size().rename('count').reset_index()
    direction.columns = ['model_said', 'gpt_said', 'count']
    direction = direction.sort_values('count', ascending=False)
    print(direction.to_string(index=False))

=================================================================
  Total compared  : 200
  Algorithm agree : 57  (28.5%)
  Disagreements   : 143  (71.5%)
=================================================================

#     Company Name                              Algorithm           GPT-4o              Matched keywords
----------------------------------------------------------------------------------------------------------------------------------
1     Sigmon Wealth Management                  unlikely            highly unlikely     'Wealth Management'(-1.0)
2     Heritage Asset Management, LLC            unlikely            highly unlikely     'Asset Management'(-1.0)
3     Pats Cleaning Service                     highly unlikely     unlikely            'Cleaning Service'(-2.0)
4     Knewsco Digital Inc.                      likely              unclear             'Digital'(+0.8)
5     Tidus Consulting                          unclear             highly unlikely     (none)
6     L&C Landholdings LLC                      unclear             highly unlikely     (none)
7     Rylie Doo’s                               unclear             likely              (none)
8     Barnett Marketing and Sales, LLC          highly likely       unclear             'Marketing'(+1.5)
9     IT Consulting Services                    unlikely            highly unlikely     'IT Consulting'(-1.0)
10    Liberty Golden Realty and Financial       unclear             highly unlikely     (none)
11    Mevaser Tech                              likely              unclear             'Tech'(+0.5)
12    BISSource Consulting Group (BCG)          unlikely            highly unlikely     'Consulting Group'(-0.8)
13    Guardian Insurance Agency LLC             unlikely            highly unlikely     'Insurance Agency'(-1.0)
14    Aislinn's Mobile Notary                   likely              unlikely            'Mobile'(+0.8)
15    CBR Roofing Plus Maintenance              highly unlikely     unlikely            'Roofing'(-2.5)
16    Bronx.Tech                                likely              unclear             'Tech'(+0.5)
17    Vision Focus Business Consulting,LLC      unlikely            highly unlikely     'Business Consulting'(-0.8)
18    Versatile Web Technologies                likely              unclear             'Web'(+0.8)
19    Digital Dust                              likely              unclear             'Digital'(+0.8)
20    Prime Pet Box                             unclear             highly likely       (none)
21    Gray Bike Software                        likely              unclear             'Software'(+0.5)
22    ERP Software Solutions                    unlikely            highly unlikely     'Software'(+0.5); 'ERP'(-1.0)
23    Bloom Online Business Management          likely              unclear             'Online'(+0.8)
24    Harvester Veterinary Hospital of Burr Ridge  highly unlikely     unlikely            'Hospital'(-1.5)
25    Internet Easy-Access, Inc                 likely              unclear             'Internet'(+0.8)
26    SPINE LIFE CHIROPRACTIC, LLC              unclear             unlikely            (none)
27    Arch Consulting Group                     unlikely            highly unlikely     'Consulting Group'(-0.8)
28    Cheshire Wellness Center                  highly likely       likely              'Wellness Center'(+2.8)
29    Costin-Hubert Insurance Agency            unlikely            highly unlikely     'Insurance Agency'(-1.0)
30    Christian Brothers Roofing & Contracting  highly unlikely     unlikely            'Roofing'(-2.5)
31    Gatsby Technology Inc.                    likely              unclear             'Technology'(+0.5)
32    ALL TURF LLC                              highly unlikely     unlikely            'TURF'(-2.5)
33    Web Optimization, Inc.                    likely              unclear             'Web'(+0.8)
34    410 Consulting                            unclear             highly unlikely     (none)
35    Xtreme Hauling                            highly unlikely     unlikely            'Hauling'(-2.0)
36    Marquee Mobile                            likely              unclear             'Mobile'(+0.8)
37    Steel Blue Fabrication, LLC               highly unlikely     unlikely            'Fabrication'(-2.5)
38    The Compuclinic/Catalyst IT Solutions     unlikely            unclear             'IT Solutions'(-1.0)
39    Fusion Marketing                          highly likely       unclear             'Marketing'(+1.5)
40    Atticus Wealth Management                 unlikely            highly unlikely     'Wealth Management'(-1.0)
41    LaserXD Sailing                           unclear             likely              (none)
42    Linka Digital                             likely              unclear             'Digital'(+0.8)
43    Landscape Ecology                         unclear             unlikely            (none)
44    Applauso Italian Learning Center, LLC     highly likely       unclear             'Learning Center'(+2.0)
45    Rockstar Remodel                          highly unlikely     unlikely            'Remodel'(-2.5)
46    Bluebonnet Speech Pathology               highly unlikely     unlikely            'Pathology'(-1.5)
47    Roadrunner Digital Mining, LLC            likely              highly unlikely     'Digital'(+0.8)
48    Pool-Martin Insurance Agency, Inc.        unlikely            highly unlikely     'Insurance Agency'(-1.0)
49    M&M Creek Valley Farm, LLC                unclear             unlikely            (none)
50    The Black Wealth Builder                  highly unlikely     unlikely            'Builder'(-2.5)
51    InteropSoft                               unclear             highly unlikely     (none)
52    MoZo Software LLC                         likely              highly unlikely     'Software'(+0.5)
53    Nadine Kureghian Insurance Agency, Inc.   unlikely            highly unlikely     'Insurance Agency'(-1.0)
54    Borgmann Construction Inc.                highly unlikely     unlikely            'Construction Inc'(-2.5)
55    Insurance Broker                          unlikely            highly unlikely     'Insurance Broker'(-1.0)
56    Silver Bullet Technology Inc.             likely              highly unlikely     'Technology'(+0.5)
57    Down Best Web Solutions                   likely              unlikely            'Web'(+0.8)
58    Hello Holiday                             unclear             likely              (none)
59    cabi wardrobe stylist                     highly likely       likely              'wardrobe'(+2.5)
60    Tech on Tap Jax                           likely              unclear             'Tech'(+0.5)
61    McCann Lawn Care                          highly unlikely     unlikely            'Lawn Care'(-2.5)
62    All Creative Executions (ACE Marketing)   highly likely       unclear             'Marketing'(+1.5)
63    aesthete mercantile + dry goods           unclear             likely              (none)
64    Yankee Bravo Digital Marketing            highly likely       unclear             'Digital Marketing'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8
65    Elephant Key Marketing                    highly likely       unclear             'Marketing'(+1.5)
66    First Class Masonry                       highly unlikely     unlikely            'Masonry'(-2.5)
67    Orleans Insurance Agency LLC              unlikely            highly unlikely     'Insurance Agency'(-1.0)
68    Datahead Software Solutions               likely              highly unlikely     'Software'(+0.5)
69    HSL Digital                               likely              unclear             'Digital'(+0.8)
70    Lillian & Associates Insurance Agency, Inc  unlikely            highly unlikely     'Insurance Agency'(-1.0)
71    Clear Sky Solar, Inc.                     unclear             unlikely            (none)
72    Tyc00n Software                           likely              highly unlikely     'Software'(+0.5)
73    Max Velocity Motorsports & Fabrication LLC  highly unlikely     unclear             'Fabrication'(-2.5)
74    Software Engineering Professionals (SEP)  likely              highly unlikely     'Software'(+0.5)
75    Conway Lawn Care, Inc.                    highly unlikely     unlikely            'Lawn Care'(-2.5)
76    Green Valley Insurance Agency             unlikely            highly unlikely     'Insurance Agency'(-1.0)
77    Subtle Tech                               likely              highly unlikely     'Tech'(+0.5)
78    Schrimpf Insurance Agency, LLC (Allstate Exclusive Agent)  unlikely            highly unlikely     'Insurance Agency'(-1.0)
79    GPS Management Consulting, Corp.          unlikely            highly unlikely     'Management Consulting'(-0.8)
80    Paceline Wealth Management, LLC           unlikely            highly unlikely     'Wealth Management'(-1.0)
81    Ahmadeus Technology Boutique              highly likely       unclear             'Boutique'(+2.5); 'Technology'(+0.5)
82    Alpenglow Mobile Massage Therapy, LLC     highly likely       likely              'Massage'(+3.0); 'Mobile'(+0.8)
83    ORIENTAL HEALING OASIS & WELLNESS CENTER  highly likely       likely              'WELLNESS CENTER'(+2.8)
84    IHT Insurance Agency Group                unlikely            highly unlikely     'Insurance Agency'(-1.0)
85    Tech-Angeles                              likely              highly unlikely     'Tech'(+0.5)
86    Pilates by Nancy                          highly likely       likely              'Pilates'(+2.8)
87    Tom Hamiltons Painting Service            unclear             unlikely            (none)
88    Redding IT Solutions, LLC                 unlikely            highly unlikely     'IT Solutions'(-1.0)
89    Independent Insurance Agency              unlikely            highly unlikely     'Insurance Agency'(-1.0)
90    O-Web Technologies, Ltd.                  likely              highly unlikely     'Web'(+0.8)
91    Timber Hill Veterinary Services           unclear             unlikely            (none)
92    Invescore Global Asset Management LLC     unlikely            highly unlikely     'Asset Management'(-1.0)
93    33 rd Annual Tinsel Triathlon & 5K        unclear             likely              (none)
94    JLB Strategy Consulting                   unlikely            highly unlikely     'Strategy Consulting'(-0.8)
95    Laura Gordillo Photography                unclear             highly likely       (none)
96    APP ARCHITECTS                            likely              highly unlikely     'APP'(+0.8)
97    Maple Ridge Photography                   unclear             highly likely       (none)
98    Prism Art and Design                      unclear             likely              (none)
99    Skull Creek Greek, LLC                    unclear             likely              (none)
100   Proficio Consulting Group, LLC            unlikely            highly unlikely     'Consulting Group'(-0.8)
101   Prime Seamless Gutters & Roofing, LLC     highly unlikely     unlikely            'Roofing'(-2.5)
102   Indaba Music                              unclear             likely              (none)
103   Thurman Technology                        likely              highly unlikely     'Technology'(+0.5)
104   Brackett's Lawn Care                      highly unlikely     unlikely            'Lawn Care'(-2.5)
105   OJ IT Solutions                           unlikely            highly unlikely     'IT Solutions'(-1.0)
106   Table Mountain Ventures, LLC & TMV Consulting Group  unlikely            highly unlikely     'Consulting Group'(-0.8)
107   Quiet Storm Massage & Bodywork            highly likely       likely              'Massage'(+3.0)
108   Roofing & Exterior Contractor - Independent Contractor  highly unlikely     unlikely            'Roofing'(-2.5)
109   Sierra West Masonry, Inc.                 highly unlikely     unlikely            'Masonry'(-2.5)
110   Nuffer Fitness                            unclear             likely              (none)
111   Mobile Realty LLC                         likely              unclear             'Mobile'(+0.8)
112   Roscoe Sports Technology                  likely              unclear             'Technology'(+0.5)
113   Woodland & Ivory                          unclear             likely              (none)
114   EJS Equities, LLC                         unclear             highly unlikely     (none)
115   Parlay App                                likely              unclear             'App'(+0.8)
116   North Central Marketing                   highly likely       unclear             'Marketing'(+1.5)
117   Simply Me Collections                     unclear             likely              (none)
118   Ramen Supply Company                      highly likely       unclear             'Ramen'(+2.8)
119   Simply Two Consulting Firm, LLC           unlikely            highly unlikely     'Consulting Firm'(-0.8)
120   Hale Speech Pathology                     highly unlikely     unlikely            'Pathology'(-1.5)
121   M3 Digital Marketing                      highly likely       unclear             'Digital Marketing'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8
122   Wild Horses Mobile Wash                   likely              unlikely            'Mobile'(+0.8)
123   Kristin Marie Jewelry                     highly likely       likely              'Jewelry'(+3.0)
124   Bavarian Window Cleaning - (360)-701-0644 - https://bavarianwindowcleaning.com  highly unlikely     unlikely            'Window Cleaning'(-2.0)
125   ULI Tech                                  likely              unclear             'Tech'(+0.5)
126   E-Commerce Processing                     highly likely       unclear             'E-Commerce'(+3.0)
127   Blin Software CO. LTD.                    likely              highly unlikely     'Software'(+0.5)
128   Rusch Technology Services LLC             likely              highly unlikely     'Technology'(+0.5)
129   Shotgun Logistics Co.                     highly unlikely     unlikely            'Logistics Co'(-2.0)
130   G’s Trucking, LLC - Transportation        highly unlikely     unlikely            'Trucking'(-2.0)
131   John Fiorentino Insurance Agency          unlikely            highly unlikely     'Insurance Agency'(-1.0)
132   BETA Consulting Group                     unlikely            highly unlikely     'Consulting Group'(-0.8)
133   Southard Strategies, LLC                  unclear             highly unlikely     (none)
134   Premier Technology Services, Inc.         likely              highly unlikely     'Technology'(+0.5)
135   Remodel Boston                            highly unlikely     unlikely            'Remodel'(-2.5)
136   Mage Mind Software LLC                    likely              highly unlikely     'Software'(+0.5)
137   "The South" Insurance Agency              unlikely            highly unlikely     'Insurance Agency'(-1.0)
138   Turner & Sons Roofing & Siding, LLC       highly unlikely     unlikely            'Roofing'(-2.5)
139   Chicago Startup Factory                   likely              unclear             'Startup'(+0.5)
140   Legends Trucking & Transportation LLC     highly unlikely     unlikely            'Trucking'(-2.0)
141   Michael trucking serv.                    highly unlikely     unlikely            'trucking'(-2.0)
142   Clear Concept Fitness (Marketing/Social Media Agency)  highly likely       likely              'Social Media Agency'(+3.5); 'Social Media'(+2.0); 'Marketin
143   M Petersen Consulting Group               unlikely            highly unlikely     'Consulting Group'(-0.8)

Disagreement breakdown by direction:
      algo_said        gpt_said  count
       unlikely highly unlikely     32
highly unlikely        unlikely     26
         likely         unclear     19
         likely highly unlikely     15
  highly likely         unclear     11
        unclear          likely     11
  highly likely          likely      8
        unclear highly unlikely      7
        unclear        unlikely      6
        unclear   highly likely      3
         likely        unlikely      3
highly unlikely         unclear      1
       unlikely         unclear      1
  highly likely   highly likely      0
         likely   highly likely      0
  highly likely highly unlikely      0
  highly likely        unlikely      0
         likely          likely      0
        unclear         unclear      0
       unlikely   highly likely      0
       unlikely          likely      0
highly unlikely   highly likely      0
       unlikely        unlikely      0
highly unlikely          likely      0
highly unlikely highly unlikely      0

## 6 · Manual Corrections

After reviewing the validation sample, add mis-classified names to `FORCE_LABEL` below.  
Valid labels: `'highly likely'`, `'likely'`, `'unclear'`, `'unlikely'`, `'highly unlikely'`.  
Re-run this cell and Section 4 onward to see updated results.

In [ ]:
# ── Manual overrides ─────────────────────────────────────────────────────────
# Map company_name → correct label (one of LABEL_ORDER)
# Example:
#   'Acme Photo Studio'  : 'highly likely',
#   'Smith Plumbing LLC' : 'highly unlikely',

FORCE_LABEL = {
    # 'Company Name Here': 'highly likely',
}

# ── Apply overrides ───────────────────────────────────────────────────────────
company_scores['fb_ad_likelihood_final'] = company_scores['fb_ad_likelihood'].copy()

if FORCE_LABEL:
    for name, label in FORCE_LABEL.items():
        if label not in LABEL_ORDER:
            print(f'WARNING: invalid label "{label}" for "{name}" — skipping')
            continue
        mask = company_scores['company_name'] == name
        if mask.sum() == 0:
            print(f'WARNING: "{name}" not found in company_scores — skipping')
        else:
            company_scores.loc[mask, 'fb_ad_likelihood_final'] = label

changed = (company_scores['fb_ad_likelihood_final'] != company_scores['fb_ad_likelihood']).sum()
print(f'Overrides applied: {changed}')
print()
print('Updated distribution:')
counts = company_scores['fb_ad_likelihood_final'].value_counts().reindex(LABEL_ORDER)
for label, n in counts.items():
    pct = n / len(company_scores) * 100
    print(f'  {label:<20}: {n:8,}  ({pct:5.1f}%)')

Overrides applied: 0

Updated distribution:
  highly likely      :   25,375  (  6.6%)
  likely             :    7,213  (  1.9%)
  unclear            :  348,072  ( 90.0%)
  unlikely           :    1,902  (  0.5%)
  highly unlikely    :    4,386  (  1.1%)

## 7 · Sanity Check — Top and Bottom Companies by P(yes)

In [25]:
show_cols = ['company_name', 'fb_ad_likelihood', 'fb_ad_prob']

print('=== TOP 30 most confidently HIGHLY LIKELY companies ===')
display(
    company_scores[company_scores['fb_ad_likelihood'] == 'highly likely']
    .sort_values('fb_ad_prob', ascending=False)
    .head(30)[show_cols]
    .reset_index(drop=True)
)

print('\n=== TOP 30 most confidently HIGHLY UNLIKELY companies ===')
display(
    company_scores[company_scores['fb_ad_likelihood'] == 'highly unlikely']
    .sort_values('fb_ad_prob', ascending=True)
    .head(30)[show_cols]
    .reset_index(drop=True)
)

print('\n=== Sample of UNCLEAR companies (closest to 0.50 probability) ===')
display(
    company_scores[company_scores['fb_ad_likelihood'] == 'unclear']
    .assign(_dist=lambda d: (d['fb_ad_prob'] - 0.5).abs())
    .sort_values('_dist')
    .head(30)[show_cols]
    .reset_index(drop=True)
)

=== TOP 30 most confidently HIGHLY LIKELY companies ===

,company_name,fb_ad_likelihood,confidence,raw_score,matched_keywords
0,"Atlanta SEO Pro, LLC - An Atlanta, GA SEO Company and Full Service Digital M...",highly likely,1.000,12.800,'Digital Marketing'(+3.5); 'SEO'(+3.5); 'Marketing Agency'(+3.5); 'Marketing...
1,Invent | SEO | Social Media Marketing | Content Driven Solutions | Digital M...,highly likely,1.000,11.300,'Social Media Marketing'(+3.5); 'SEO'(+3.5); 'Social Media'(+2.0); 'Marketin...
2,Oakwood Lane (eCommerce & Social Media Marketing Consulting),highly likely,1.000,10.000,'Social Media Marketing'(+3.5); 'eCommerce'(+3.0); 'Social Media'(+2.0); 'Ma...
3,Vertical Web - Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Web...
4,"Jolly Sherpa, Digital Marketing Agency",highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
5,SEO & Digital Marketing,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'SEO'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8)
6,New England Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
7,Permian Edge Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
8,Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
9,"MSE, LLC. | Digital Marketing Agency",highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
10,Savvy Nerds Local Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
11,Keep It Social Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
12,Digital Marketing Agency CORDOBA,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
13,ODG Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
14,Local Moguls / Digital Marketing & SEO,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'SEO'(+3.5); 'Marketing'(+1.5); 'Digital'(+0.8)
15,KCV Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
16,VIral SVN - Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
17,Benjamin Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
18,ddZ - Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
19,Craft & Clover - A Digital Marketing Agency,highly likely,1.000,9.300,'Digital Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5); 'Dig...
20,"The Inn and Spa at Benicia Bay, Vino Paladini Restaurant and Wine Bar",highly likely,1.000,8.600,'Spa'(+3.0); 'Restaurant'(+2.8); 'Wine Bar'(+2.8)
21,Jolly Sherpa - Growth Marketing Agency,highly likely,1.000,8.500,'Growth Marketing'(+3.5); 'Marketing Agency'(+3.5); 'Marketing'(+1.5)
22,"Foreign Affair Collections, E-Commerce Clothing Boutique",highly likely,1.000,8.500,'E-Commerce'(+3.0); 'Clothing'(+3.0); 'Boutique'(+2.5)
23,Blush Bridal and Formal Wear,highly likely,1.000,8.300,'Wear'(+3.0); 'Blush'(+2.5); 'Bridal'(+2.8)
24,Bronzed N Glow Beauty Boutique,highly likely,1.000,8.000,'Boutique'(+2.5); 'Beauty'(+3.0); 'Glow'(+2.5)
25,Shelly's Activewear Boutique,highly likely,1.000,8.000,'Activewear'(+3.0); 'Boutique'(+2.5); 'Activewear'(+2.5)
26,Waggin' Tails Pet Boutique and Spa,highly likely,1.000,8.000,'Boutique'(+2.5); 'Spa'(+3.0); 'Pet Boutique'(+2.5)
27,ATE20 Sneaker Boutique and Art Gallery,highly likely,1.000,8.000,'Sneaker'(+3.0); 'Boutique'(+2.5); 'Art Gallery'(+2.5)
28,Ascenial - eCommerce Advertising Agency,highly likely,1.000,8.000,'Advertising Agency'(+3.5); 'eCommerce'(+3.0); 'Advertising'(+1.5)
29,Wellness Spa Retreat Boutique,highly likely,1.000,8.000,'Boutique'(+2.5); 'Spa'(+3.0); 'Retreat'(+2.5)

=== TOP 30 most confidently HIGHLY UNLIKELY companies ===

,company_name,fb_ad_likelihood,confidence,raw_score,matched_keywords
0,"Lewis Lawn Care and Masonry, LLC",highly unlikely,0.007,-5.000,'Lawn Care'(-2.5); 'Masonry'(-2.5)
1,"LATHAM LAWN CARE AND PRESSURE WASH, LLC",highly unlikely,0.011,-4.500,'LAWN CARE'(-2.5); 'PRESSURE WASH'(-2.0)
2,Showcase Lawn Care & Services DBA Frankie B's Hauling,highly unlikely,0.011,-4.500,'Lawn Care'(-2.5); 'Hauling'(-2.0)
3,"O & W Mortuary Services, PLLC",highly unlikely,0.047,-3.000,'Mortuary'(-3.0)
4,Sterling Lewis Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
5,"Ponte Vedra Valley: Funeral Home, Cremation Center & Cemetery",highly unlikely,0.047,-3.000,'Funeral'(-3.0)
6,THE FAT FUNERAL ®™,highly unlikely,0.047,-3.000,'FUNERAL'(-3.0)
7,Potti & Marc F. Burr Funeral Homes,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
8,Christians Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
9,Daniels Chapel of the Roses Funeral Home & Crematory,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
10,"Dodd & Reed, Adams-Reed Funeral Homes",highly unlikely,0.047,-3.000,'Funeral'(-3.0)
11,Joseph F. Nardone Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
12,Florida Security and Funeral Escort,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
13,"Hillis, Combs & Nestor Funeral Home",highly unlikely,0.047,-3.000,'Funeral'(-3.0)
14,Spicer-Mullikin Funeral Homes Inc,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
15,Suburban Memorial Gardens Cemetery,highly unlikely,0.047,-3.000,'Cemetery'(-3.0)
16,Stockert-Paletti Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
17,Adamson Funeral & Cremation Services,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
18,Grace Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
19,Price-Murphy Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
20,Kalkaska Funeral Home & Cremation Services,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
21,"Koskey Funeral Home, Inc.",highly unlikely,0.047,-3.000,'Funeral'(-3.0)
22,Troutman Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
23,Regency Mortuary,highly unlikely,0.047,-3.000,'Mortuary'(-3.0)
24,Liming Family Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
25,RSGibbs Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
26,RS Gibbs Life Celebrations Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
27,Toombs Funeral Home,highly unlikely,0.047,-3.000,'Funeral'(-3.0)
28,"Brown's Funeral Home, Ltd",highly unlikely,0.047,-3.000,'Funeral'(-3.0)
29,Roth Cemetery Services,highly unlikely,0.047,-3.000,'Cemetery'(-3.0)

=== Sample of UNCLEAR companies (closest to 0.50 confidence) ===

,company_name,fb_ad_likelihood,confidence,raw_score,matched_keywords
0,Karla Consulting Services,unclear,0.500,0.000,(none)
1,Wheelhouse Press,unclear,0.500,0.000,(none)
2,PlusAI,unclear,0.500,0.000,(none)
3,Locus Energy,unclear,0.500,0.000,(none)
4,Meditation Without Borders,unclear,0.500,0.000,(none)
5,"Black Border Media, LLC",unclear,0.500,0.000,(none)
6,"M.A.W. Consulting, LLC",unclear,0.500,0.000,(none)
7,ElegrootSolutions LLC,unclear,0.500,0.000,(none)
8,Versatile Image,unclear,0.500,0.000,(none)
9,Kenneth Kendall Coaching,unclear,0.500,0.000,(none)
10,K2 Design & Production,unclear,0.500,0.000,(none)
11,Discovery Media Services,unclear,0.500,0.000,(none)
12,Data Oasys,unclear,0.500,0.000,(none)
13,Gettysburg Print and Frame,unclear,0.500,0.000,(none)
14,Solid For Life,unclear,0.500,0.000,(none)
15,Schurr Power LLC,unclear,0.500,0.000,(none)
16,Woander,unclear,0.500,0.000,(none)
17,Woander Travel,unclear,0.500,0.000,(none)
18,"F2F Solutions, Inc.",unclear,0.500,0.000,(none)
19,Paperclip - The Diaper Bag For Life,unclear,0.500,0.000,(none)
20,CryptoWise.ai,unclear,0.500,0.000,(none)
21,Graphite,unclear,0.500,0.000,(none)
22,"Erica Reagan CPA, LLC",unclear,0.500,0.000,(none)
23,Strong Tower Advisors,unclear,0.500,0.000,(none)
24,A4DevCR,unclear,0.500,0.000,(none)
25,"A.S.K. Accountax Consultants, Inc.",unclear,0.500,0.000,(none)
26,Bela Sono Music,unclear,0.500,0.000,(none)
27,Whole Nutrition Services (self-employed),unclear,0.500,0.000,(none)
28,"Employment Insight, LLC",unclear,0.500,0.000,(none)
29,Kittoe Mowing Co.,unclear,0.500,0.000,(none)

## 8. Save Results

In [26]:
# Merge final label back onto entrepreneurs
_drop = [c for c in ['fb_ad_likelihood', 'fb_ad_prob'] if c in entrepreneurs.columns]
if _drop:
    entrepreneurs = entrepreneurs.drop(columns=_drop)

entrepreneurs = entrepreneurs.merge(
    company_scores[['company_name', 'fb_ad_prob', 'fb_ad_likelihood_final']]
    .rename(columns={'fb_ad_likelihood_final': 'fb_ad_likelihood'}),
    on='company_name',
    how='left'
)

print('Final distribution across entrepreneur rows:')
counts = entrepreneurs['fb_ad_likelihood'].value_counts().reindex(LABEL_ORDER)
for label, n in counts.items():
    pct = n / len(entrepreneurs) * 100
    print(f'  {label:<20}: {n:8,}  ({pct:5.1f}%)')

out_path = '/shared/share_scp/coresignal/entrepreneurs_marketing_oriented_latest.pkl'
entrepreneurs.to_pickle(out_path)
print(f'\nSaved {len(entrepreneurs):,} rows to {out_path}')

scores_path = '/shared/share_scp/coresignal/company_marketing_scores_latest.pkl'
company_scores.to_pickle(scores_path)
print(f'Saved company scores ({len(company_scores):,} unique names) to {scores_path}')

Final distribution across entrepreneur rows:
  highly likely      :   70,884  (  6.1%)
  likely             :   25,550  (  2.2%)
  unclear            : 1,047,496  ( 89.6%)
  unlikely           :    5,412  (  0.5%)
  highly unlikely    :   10,702  (  0.9%)

Saved 1,169,264 rows to /shared/share_scp/coresignal/entrepreneurs_marketing_oriented_latest.pkl
Saved company scores (386,948 unique names) to /shared/share_scp/coresignal/company_marketing_scores_latest.pkl